### ISSUE TITLE
Trang chủ (HOME) chưa có logout đâu

### ISSUE THREAD

**Issue by badungphan99** [badungphan99/QuanLyTapHuan#3]
Đăng nhập vào rồi nhưng chưa thấy nút logut đâu cả nhé :))
![Screenshot from 2020-11-06 10-02-49](https://user-images.githubusercontent.com/40152512/98321273-47733000-2017-11eb-86b3-a27977f6d055.png)

**Comment by quynhnhi0124** [comment]
![2020-11-09](https://user-images.githubusercontent.com/53897670/98482914-13765580-2237-11eb-9bb3-48db2b6c85a8.png)

**Comment by quynhnhi0124** [comment]
t thêm r nha
