### ISSUE TITLE
Quản lý chương trình tập huấn

### ISSUE THREAD

**Issue by hieuphamnhat** [badungphan99/QuanLyTapHuan#6]
Đã có các chức năng: Thêm, Sửa, Xem các chương trình học

**Comment by hieuphamnhat** [comment]
Các bạn Front-end nếu có thời gian thì vào xem hộ tớ trang quản lý chương trình học nhé. /program
Nếu có thời gian thì sửa lại giao diện cho nó đồng bộ với giao diện các trang khác.

**Comment by quynhnhi0124** [comment]
t đang xem nhen :x

**Comment by hieuphamnhat** [comment]
xong rồi thì cmt vào đây nhé các bạn

**Comment by hieuphamnhat** [comment]
các bạn front end kéo code ở nhánh t về code nhé.
Sửa cả giao diện programs, courses, teachers luôn nhé. Mấy cái này đang giống nhau. Làm 1 cái rồi cho mấy cái kia kế thừa cx dc. nhớ giữ name vs id như cũ nhé

**Comment by hieukai** [comment]
Nhóm frontend nhớ kéo cái footer ở trang chủ xuống bé lại nhé. T nhắc từ buổi họp meet gần nhất rồi=))). Cho nó vừa đủ chứa nội dung thôi, hiện h đang to quá=)))

**Comment by quynhnhi0124** [comment]
t sửa gd phần button r các thứ như c bảo r nhớ (branch check),, c xem lại hộ t cái xóa giáo viên vs nhen, t checkout sang branch của c hình như cx k xóa dc í

**Comment by hieuphamnhat** [comment]
để t check

**Comment by hieuphamnhat** [comment]
Xóa dc r nhé

**Comment by hieuphamnhat** [comment]
t tích hợp giao diện sag nhánh pnhieu r nhé.

**Comment by quynhnhi0124** [comment]
Oki nha Hiếu ơii
