### ISSUE TITLE
Quản lý các khóa tập huấn

### ISSUE THREAD

**Issue by hieuphamnhat** [badungphan99/QuanLyTapHuan#7]
Đã có các chức năng: Xem các khóa tập huấn.
Cần fix:
 +Thêm, sửa các khóa tập huấn theo thiết kế mới của DB.
 +Xem giáo viên đang dạy khóa học (chưa test với DB mới).
 +Xem danh sách học viên đã tham gia.

**Comment by hamyho123** [comment]
okiee

**Comment by hieuphamnhat** [comment]
Đã xong các chức năng xem, sửa, thêm các khóa tập huấn theo DB mới

**Comment by hieuphamnhat** [comment]
*Đã fix xong: 
1)Xem giảng viên của khóa học
2)Thêm giảng viên vào khóa học
*Cần làm:
1) Xóa giảng viên khỏi khóa học
2) Thêm, xem, xóa học viên của khóa học

**Comment by hieuphamnhat** [comment]
@hamyho123 
*Đã fix xong:
1)Xem giảng viên của khóa học
2)Thêm giảng viên vào khóa học
3)Xóa giảng viên khỏi khóa học
*Cần làm:
Thêm, xem, xóa học viên của khóa học

**Comment by hieuphamnhat** [comment]
@hamyho123 
Đã xong:
Thêm, xem, xóa học viên của khóa học.
Chưa xong:
Đăng ký học.
