### ISSUE TITLE
báo cáo chủ nhật

### ISSUE THREAD

**Issue by hieuphamnhat** [badungphan99/QuanLyTapHuan#8]

**Comment by hieuphamnhat** [comment]
@hieukai 
 XONG:
+ Xem, thêm, sửa các khóa học của 1 chương trình.
+ Xem, thêm, sửa các chương trình tập huấn.
+ Xem, thêm giảng viên vào khóa học bất kỳ
+ Xóa giảng viên của 1 khóa bất kỳ
CHƯA:
+ Xem. thêm, xóa học viên của 1 khóa bất kỳ

**Comment by hoangi19** [comment]
@hoangi19 
* xong 
* xem thông tin user
* sửa thông tin user
* cần làm : lọc theo thông tin
