### ISSUE TITLE
Đăng ký học

### ISSUE THREAD

**Issue by hieuphamnhat** [badungphan99/QuanLyTapHuan#9]
Các việc cần làm:
+ Tại trang chủ của WEB liệt kê các khóa học có trong DB(chỉ liệt kê các trường: tên khóa học, địa điểm, trạng thái). Mặc định khi login thành công sẽ dẫn tới trang chủ và nhìn thấy ngay các khóa này.
+ Login vào account đã được tạo trên DB có id = role == 4 (tương ứng với account student).
+ Tại mỗi khóa học ở trang chủ, xuất hiện 1 nút đăng ký(hoặc: ghi danh ). Hệ thống sẽ kiểm tra trạng thái của khóa học. Nếu active(status == 1), mặc định đăng ký thành công. Sau khi đăng ký thành công, redirect ra trang chủ kèm status("Đăng ký thành công").

**Comment by hamyho123** [comment]
![st](https://user-images.githubusercontent.com/73026295/101125465-e21d5980-362b-11eb-8a56-1e57a33bf7cf.png)

**Comment by hamyho123** [comment]
login student

**Comment by Dieungan99** [comment]
t sửa lại phần trang chủ r nhé

**Comment by hieuphamnhat** [comment]
Update
Đã xong:
+Hiển thị toàn bộ Khóa học trong trang home
+Hiển thị các Khóa user đó đã đăng ký
Chưa:
Đăng ký học

**Comment by hieuphamnhat** [comment]
xong: đăng ký học by @hamyho123
